### ISSUE TITLE
widget.value == null

### ISSUE THREAD

**Issue by zangen** [icemanbsi/searchable_dropdown#6] opened 2019-12-26 08:54 UTC
I use your demo,i had this problen,
family: Roboto, size: 15.0, weight: 400, baseline: ideographic, decoration: TextDecoration.none, softWrap: wrapping at box width, overflow: clip):
'package:searchable_dropdown/searchable_dropdown.dart': Failed assertion: line 90 pos 12: 'widget.value == null ||
widget.items.where((DropdownMenuItem item) => item.value == widget.value).length == 1': is not true.

**Comment by FarhanSaikh** [comment] 2020-02-01 14:10
@ zangen , I Got same issue. did you able to solve the problem ?

**Comment by tonytang0114** [comment] 2020-02-05 06:44
I have the same problem
Found out that the source code here somehow is not true


    assert(widget.value == null ||
        widget.items.where((DropdownMenuItem<T> item) => item.value == widget.value).length == 1);
    _selectedIndex = null;
    for (int itemIndex = 0; itemIndex < widget.items.length; itemIndex++) {
      if (widget.items[itemIndex].value == widget.value) {
        _selectedIndex = itemIndex;
        return;
      }
    }
  }

**Comment by tonytang0114** [comment] 2020-02-05 06:47
@FarhanSaikh  For a temporary fix, i think you can clone the dart file and delete the lines above. I will also check why the assertion will return false by the way

**Comment by lwcinfo** [comment] 2020-02-05 18:58
replace this line
`assert(widget.value == null || widget.items.where((DropdownMenuItem<T> item) => item.value == widget.value).length == 1);`


for this

`assert(widget.value == null || widget.items.where((DropdownMenuItem<T> item) => item.value == widget.value).length <= 1);`

**Comment by lcuis** [comment] 2020-02-07 04:02
Hello @zangen @FarhanSaikh @tonytang0114 @lwcinfo ,

Thanks for reporting this issue, finding the root cause and finding a fix.

PR #10 has just been merged.
An new parameter has been added defaulted to true to allow the avoidance of the items check part of this assert.
```
assertUniqueValue: false,
```
Can you please let us know whether adding the above line to your call solves your issue with the latest version of the plugin?

**Comment by lcuis** [comment] 2020-02-11 10:43
Hello @zangen @FarhanSaikh @tonytang0114 @lwcinfo ,

I recently realized that the latest version of the plugin is not available on pub.dev and that if you want to try it, you would have to either wait for the publication or temporarily use the following in your `pubspec.yaml` file:
```
  searchable_dropdown:
    git:
      url: https://github.com/icemanbsi/searchable_dropdown.git
```

Sorry for the inconvenience.

**Comment by icemanbsi** [comment] 2020-03-02 09:38
Hi @zangen @FarhanSaikh @tonytang0114 @lwcinfo 
I've published the update (thanks @lcuis ) on pub.dev.
I'll close this issue and feel free to reopen if you think this issue is not solved yet.
Thanks

**Closed by icemanbsi** 2020-03-02 09:38 UTC
